services:
  - type: web
    name: roamly
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: openai/gpt-oss-20b
      - key: DATABASE_URL
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: AVIATION_STACK_API_KEY
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: LANGCHAIN_TRACING
        value: "false"
      - key: LANGCHAIN_ENDPOINT
        value: https://api.smith.langchain.com
      - key: LANGCHAIN_API_KEY
        sync: false
      - key: LANGCHAIN_PROJECT
        value: Roamly
      - key: MCP_RETRIES
        value: "2"
      - key: MCP_CACHE_TTL_SECONDS
        value: "300"
